name: Docker Push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Image Name
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/$OWNER/$REPO" >> $GITHUB_ENV

      - name: Debug app.py
        run: |
          grep -n 'methods=\["PUT"\]' app.py
          git rev-parse HEAD
          sha256sum app.py

      - name: Build Image
        run: |
          docker build \
            -t $IMAGE:latest \
            -t $IMAGE:${{ github.sha }} \
            .

      - name: Check image
        run: |
          docker run --rm $IMAGE:${{ github.sha }} \
          grep -n 'methods=\["PUT"\]' /app/app.py

      - name: Debug
        run: |
          echo "IMAGE=$IMAGE"

      - name: Push Image
        run: |
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
