name: Hello World

on:
  push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hostname
        run: hostname

      - name: Current User
        run: whoami

      - name: Current Path
        run: pwd

      - name: OS Info
        run: uname -a

      - name: List Files
        run: ls -la